# Generated by Django 4.2.6 on 2026-01-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
